### ISSUE TITLE
Problem when running through the pipeline

### ISSUE THREAD

**Issue by sctiendat** [googlevr/seurat#15]
Hello,
I used the Seurat pipeline encoder for Windows at https://github.com/ddiakopoulos/seurat/releases
I tried to capture the example scene at Seurat Unity Plugin Project.
But I had a error:

> C:\seurat-compiled-msvc2017-x64>seurat-pipeline-msvc2017-x64.exe -input_path C:\seuratOutput\manifest.json -output_path C:\seuratResult
Reading input: [                                                                                             ] 00:00:00
ERROR: Point is outside of the frustum used for binning.  Possible causes for this problem: geometry inside the headbox, incorrect matrices, incorrect depth values, other errors in the generation process. (Showing only the first error)

 Does anyone have a solution? I tried many option at Capture Headbox script. But It's not working.

**Comment by ChristophGeske** [comment]
How did you solve the issue? Have the same isse sometimes. I do not have the issue if I use the standard scene or add a standard unity object. But adding asset store objects triggered this issue.

**Comment by sctiendat** [comment]
Hmm...
I don't remember exactly. but I think the problem in your objects, maybe the objects near your headbox. 
"Point is outside of the frustum used for binning". 
You can remove some objects and try again.
