### ISSUE TITLE
Create Scene with transparent background

### ISSUE THREAD

**Issue by squidy5** [googlevr/seurat#28]
When using seurat on a scene with a completly transparent skybox, all transparent areas are painted black in the final output textrue. Is it possible to create a scene that preserves the orignal background transparency?

**Comment by Podden** [comment]
Found a solution for Unity:

Change Camera Background to Render Solid Color with zero alpha

In CaptureBuilder.cs:
Change Line 477 to:
`view.depth_image_file.color.channel_alpha = "A";`
Change Line 457 to:
`WriteImage(color_render_texture_, Texture2DFromDynamicRange(), PathCombine(export_path, color_image_name), false);`
